In [73]:
from google.colab import files
import pandas as pd


In [74]:
filename_0 = "/content/Social_Network_Ads_1.csv"
df0 = pd.read_csv(filename_0)

In [75]:
filename_1 = "/content/Social_Network_Ads_2.csv"
df1 = pd.read_csv(filename_1)

In [76]:
filename_2 = "/content/Social_Network_Ads_3.csv"
df2 = pd.read_csv(filename_2)

In [77]:
filename_3 = "/content/Social_Network_Ads_4.csv"
df3 = pd.read_csv(filename_3)

In [78]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [79]:
df0

User ID  Gender  Age  EstimatedSalary  Purchased
0   15624510    Male   19            19000          0
1   15810944    Male   35            20000          0
2   15668575  Female   26            43000          0
3   15603246  Female   27            57000          0
4   15804002    Male   19            76000          0
..       ...     ...  ...              ...        ...
95  15709441  Female   35            44000          0
96  15710257  Female   35            25000          0
97  15582492    Male   28           123000          1
98  15575694    Male   35            73000          0
99  15756820  Female   28            37000          0

[100 rows x 5 columns]

In [80]:
x0 = df0.iloc[:,2:4]
y0 = df0.iloc[:,-1]


In [81]:
x1 = df1.iloc[:,2:4]
y1 = df1.iloc[:,-1]

In [82]:
x2 = df2.iloc[:,2:4]
y2 = df2.iloc[:,-1]

In [83]:
x3 = df3.iloc[:,2:4]
y3 = df3.iloc[:,-1]

In [84]:
from sklearn.model_selection import train_test_split

In [85]:
X_train0, X_test0, y_train0, y_test0 = train_test_split(x0,y0,test_size=0.3,random_state=42)


In [121]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(x1,y1,test_size=0.3,random_state=42)


In [87]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(x2,y2,test_size=0.3,random_state=42)

In [88]:
X_train3, X_test3, y_train3, y_test3 = train_test_split(x3,y3,test_size=0.3,random_state=42)

In [89]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [90]:
X_train0 = scaler.fit_transform(X_train0)


In [91]:
X_train1 = scaler.fit_transform(X_train1)

In [92]:
X_train2 = scaler.fit_transform(X_train2)

In [93]:
X_train3 = scaler.fit_transform(X_train3)

In [94]:
X_test0 = scaler.transform(X_test0)

In [95]:
X_test1 = scaler.transform(X_test1)

In [96]:
X_test2 = scaler.transform(X_test2)

In [97]:
X_test3 = scaler.transform(X_test3)

In [98]:
from sklearn.linear_model import LinearRegression
regression = LinearRegression()

In [99]:
from sklearn.metrics import mean_squared_error

Client - 0

In [100]:
regression.fit(X_train0,y_train0)

LinearRegression()

In [101]:
print(regression.coef_)
print(regression.intercept_)

[0.26556591 0.10702126]
0.21428571428571425


In [181]:
coef_0 = regression.coef_
intr_0 = regression.intercept_
intr_0

0.6714285714285714

In [103]:
reg_pred=regression.predict(X_test0)
print(mean_squared_error(y_test0,reg_pred))

0.3732225253787204


Client - 1

In [104]:
regression.fit(X_train1,y_train1)

LinearRegression()

In [105]:
print(regression.coef_)
print(regression.intercept_)

[0.01188944 0.19454577]
0.1


In [182]:
coef_1 = regression.coef_
intr_1 = regression.intercept_
intr_1

0.6714285714285714

In [107]:
reg_pred=regression.predict(X_test1)
print(mean_squared_error(y_test1,reg_pred))

0.022436474614115905


Client - 2

In [108]:
regression.fit(X_train2,y_train2)

LinearRegression()

In [109]:
print(regression.coef_)
print(regression.intercept_)

[0.19207856 0.21104773]
0.5000000000000001


In [183]:
coef_2 = regression.coef_
intr_2 = regression.intercept_
intr_2

0.6714285714285714

In [111]:
reg_pred=regression.predict(X_test2)
print(mean_squared_error(y_test2,reg_pred))

0.13735977377273098


Client - 3

In [112]:
regression.fit(X_train3,y_train3)

LinearRegression()

In [113]:
print(regression.coef_)
print(regression.intercept_)

[0.28445042 0.09620533]
0.6714285714285714


In [184]:
coef_3 = regression.coef_
intr_3 = regression.intercept_
intr_3

0.6714285714285714

In [115]:
reg_pred=regression.predict(X_test3)
print(mean_squared_error(y_test3,reg_pred))

0.14843644297527286


Global Model

In [116]:
avg_m1 = (coef_0[0] + coef_1[0] + coef_2[0] + coef_3[0]) / 4
avg_m1

0.18849608431710124

In [117]:
avg_m2 = (coef_0[1] + coef_1[1] + coef_2[1] + coef_3[1]) / 4
avg_m2

0.15220502303432157

In [118]:
avg_intr = (intr_0 + intr_1 + intr_2 + intr_3) / 4
avg_intr

0.37142857142857144

In [119]:
def linear_regression_hard_code(x1, x2):

    slope1 = 0.003906687743648694
    slope2 = -0.03502204188365562
    intercept = 0.49137931034482757

    # Calculate predicted y value
    y_predicted = slope1 * x1 + slope2 * x2 + intercept

    return y_predicted




In [122]:
filename = "/content/Social_Network_Ads_1.csv"
df = pd.read_csv(filename)

In [123]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [125]:
col_1 = df['Age']

In [126]:
col_2 = df['EstimatedSalary']

In [127]:
predicted_y_values = linear_regression_hard_code(col_1, col_2)
print(predicted_y_values)

0     -664.853189
1     -699.812724
2    -1505.354848
3    -1995.659527
4    -2661.109577
         ...     
95   -1540.341729
96    -874.922934
97   -4307.110385
98   -2555.980944
99   -1295.214783
Length: 100, dtype: float64


In [128]:
data = pd.DataFrame()

In [130]:
data['y_actual'] = df['Purchased']

In [131]:
data['y_pred'] = predicted_y_values

In [132]:
data.head()

y_actual       y_pred
0         0  -664.853189
1         0  -699.812724
2         0 -1505.354848
3         0 -1995.659527
4         0 -2661.109577

In [133]:
# Calculate squared errors
data['Squared_Error'] = (data['y_actual'] - data['y_pred'])**2

# Calculate mean squared error
mse = np.mean(data['Squared_Error'])

print("Mean Squared Error:", mse)


Mean Squared Error: 5382595.73648028


Naive Bayes Classifier

In [134]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import mean_squared_error

# instantiate the model
gnb = GaussianNB()




Client-0

In [135]:
# fit the model
gnb.fit(X_train0, y_train0)

GaussianNB()

In [136]:
y_pred0 = gnb.predict(X_test0)

In [137]:
mse0 = mean_squared_error(y_test0, y_pred0)

print("Mean Squared Error:", mse0)

Mean Squared Error: 0.13333333333333333


Client - 1

In [138]:
# fit the model
gnb.fit(X_train1, y_train1)

GaussianNB()

In [139]:
y_pred1 = gnb.predict(X_test1)

In [140]:
mse1 = mean_squared_error(y_test1, y_pred1)

print("Mean Squared Error:", mse1)

Mean Squared Error: 0.03333333333333333


Client - 2

In [141]:
# fit the model
gnb.fit(X_train2, y_train2)

GaussianNB()

In [142]:
y_pred2 = gnb.predict(X_test2)

In [143]:
mse2 = mean_squared_error(y_test2, y_pred2)

print("Mean Squared Error:", mse2)

Mean Squared Error: 0.13333333333333333


Client - 3

In [144]:
# fit the model
gnb.fit(X_train3, y_train3)

GaussianNB()

In [145]:
y_pred3 = gnb.predict(X_test3)

In [146]:
mse3 = mean_squared_error(y_test3, y_pred3)

print("Mean Squared Error:", mse3)

Mean Squared Error: 0.06666666666666667


Global model

In [147]:
filename_GM = "/content/Social_Network_Ads_2.csv"
dataFrame = pd.read_csv(filename_GM)

In [148]:
x = dataFrame.iloc[:,2:4]
y = dataFrame.iloc[:,-1]

In [149]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [150]:
# fit the model
gnb.fit(X_train, y_train)

GaussianNB()

In [151]:
y_pred = gnb.predict(X_test)

In [152]:
mse = mean_squared_error(y_test, y_pred)

print("Mean Squared Error:", mse)

Mean Squared Error: 0.03333333333333333


Logistic Regression

In [153]:
# train a logistic regression model on the training set
from sklearn.linear_model import LogisticRegression


# instantiate the model
logreg = LogisticRegression(solver='liblinear', random_state=0)

Client - 0

In [154]:
# fit the model
logreg.fit(X_train0, y_train0)

LogisticRegression(random_state=0, solver='liblinear')

In [155]:
y_pred_0 = logreg.predict(X_test0)

In [156]:
coefficients_0 = logreg.coef_
intercept_0 = logreg.intercept_


In [157]:
mse_0 = mean_squared_error(y_test0, y_pred_0)

print("Mean Squared Error:", mse_0)

Mean Squared Error: 0.13333333333333333


Client - 1

In [158]:
# fit the model
logreg.fit(X_train1, y_train1)

LogisticRegression(random_state=0, solver='liblinear')

In [159]:
y_pred_1 = logreg.predict(X_test1)

In [160]:
coefficients_1 = logreg.coef_
intercept_1 = logreg.intercept_

In [161]:
mse_1 = mean_squared_error(y_test1, y_pred_1)

print("Mean Squared Error:", mse_1)

Mean Squared Error: 0.1


Client - 2

In [162]:
# fit the model
logreg.fit(X_train2, y_train2)

LogisticRegression(random_state=0, solver='liblinear')

In [163]:
y_pred_2 = logreg.predict(X_test2)

In [164]:
coefficients_2 = logreg.coef_
intercept_2 = logreg.intercept_

In [165]:
mse_2 = mean_squared_error(y_test2, y_pred_2)

print("Mean Squared Error:", mse_2)

Mean Squared Error: 0.16666666666666666


Client - 3

In [166]:
logreg.fit(X_train3, y_train3)

LogisticRegression(random_state=0, solver='liblinear')

In [167]:
y_pred_3 = logreg.predict(X_test3)

In [168]:
coefficients_3 = logreg.coef_
intercept_3 = logreg.intercept_

In [169]:
coefficients_3

array([[1.82671299, 0.69482274]])

In [170]:
mse_3 = mean_squared_error(y_test3, y_pred_3)

print("Mean Squared Error:", mse_3)

Mean Squared Error: 0.16666666666666666


In [171]:
coefficients_2

array([[1.05220146, 1.11266281]])

In [172]:
coefficients_1

array([[-2.98676298e-01,  7.44306126e-05]])

In [173]:
coefficients_3

array([[1.82671299, 0.69482274]])

In [174]:
coefficients_0

array([[1.71474535, 0.80963598]])

In [175]:
avg_c1 = (-0.13961168+0.00263201+0.23383437+-0.03436674 )/4

In [176]:
avg_c2 = (-0.15498016+ -0.18304026+0.05313742+ -0.27136683)/4

In [177]:
import numpy as np

class LogisticRegression:
    def __init__(self, coefficients=None, bias=0):
        self.coefficients = coefficients
        self.bias = bias

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def predict(self, X):
        linear_model = np.dot(X, self.coefficients) + self.bias
        y_predicted = self.sigmoid(linear_model)
        y_predicted_cls = [1 if i > 0.5 else 0 for i in y_predicted]
        return y_predicted_cls




In [178]:
# Example usage
if __name__ == "__main__":
    # Example data
    #X = np.array([[2, 3], [4, 5], [6, 7], [8, 9]])

    # Coefficients and bias
    coefficients = np.array([avg_c1, avg_c2])
    bias = (intercept_3 + intercept_2 + intercept_1 + intercept_0)/4

    # Initialize the logistic regression model with coefficients and bias
    model = LogisticRegression(coefficients=coefficients, bias=bias)

    # Predict class labels
    y_pred = model.predict(X_test)
    print("Predictions:", y_pred)

Predictions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


<ipython-input-177-cc6774660696>:9: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


In [179]:
mse_ = mean_squared_error(y_test, y_pred)

print("Mean Squared Error:", mse_)

Mean Squared Error: 0.0
